language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# gradle 의존성을 Travis CI 서버의 Home에 캐시하여, 같은 의존성은 다음 배포때부터 다시 받지 않게 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# 실제로 배포에 필요한 파일만 압축하여 s3에 업로드한다
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy
  - cp appspec.yml before-deploy
  - cp build/libs/*.jar before-deploy
  - cd before-deploy && zip -r before-deploy *
  - cd .. && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY        # Travis-CI environment variables
    secret_access_key: $AWS_SECRET_KEY    # Travis-CI environment variables
    bucket: springboot-webservice-build-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-build-bucket
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - alicesister1@gmail.com
    on_success: never