# AppSpec 파일 구조. https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-structure.html
version: 0.0
os: linux
files:
  - source: /  # 디렉터리 내의 모든 파일을 인스턴스에 복사. appspecs.yml 파일의 상대적 경로 사용
    destination: /home/ec2-user/app/step2/zip  # 인스턴스에 파일이 복사되어야 하는 위치를 식별
    overwrite: yes

# 'files' 섹션의 파일 및 디렉터리/폴더가 인스턴스에 복사된 후 이러한 파일 및 디렉터리/폴더에 특수 권한(있는 경우)이 어떻게 적용되어야 하는지를 지정
permissions:
  - object: /  # 파일 시스템 객체가 인스턴스로 복사된 후 지정한 권한이 적용되는 파일/디렉터리
    pattern: "**"  # 권한을 적용할 패턴
    owner: ec2-user  # 복사 잡업 후 지정할 소유자 이름
    group: ec2-user  # 복사 작업 후 지정할 그룹 이름

hooks:
  ApplicationStart:
    - location: deploy.sh  # 스크립트 파일 위치. bundle root 기준
      timeout: 60  # 스크립트 실행이 timeout 초 이상일 경우 실패 처리
      runas: ec2-user  # 스크립트 실행 user